export { default as Home } from './home/Home'
export { default as Nav } from './nav/Nav'
export { default as Projects } from './projects/Projects'
export { default as Socials } from './Socials'
export { default as About } from './about/About'
export { default as Skills } from './Skills'
export { default as Mail } from './mail/Mail'
